defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/English
    disabled: false
    languageCode: en-gb
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Reference, Tutorials, and Explanations
    title: Project Documentation
    weight: 1
  yue:
    contentDir: content/Cantonese
    disabled: false
    languageCode: zh-hk
    languageDirection: ltr
    languageName: 粵語
    params:
      subtitle: 參考、教學和說明
    title: 項目文檔
    weight: 2
